module.exports = {
  button: {
    backgroundColor: 'white',
    border: 'none',
    borderBottom: '1px solid',
    borderColor: 'gray.4',
    cursor: 'pointer',
    fontSize: '1rem',
    margin: '0',
    overflow: 'hidden',
    padding: '.5rem 1rem',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    userSelect: 'none',
    whiteSpace: 'nowrap',
    width: '100%',
    '&:hover': {
      backgroundColor: 'lightLight',
      opacity: '1.0',
    },
  },
  text: {
    fontSize: '.75rem',
    fontVariant: 'small-caps',
    fontWeight: '200',
    lineHeight: '1rem',
    margin: '0 1em 0 0',
    verticalAlign: 'middle',
  },
}
