module.exports = {
  button: {
    borderLeft: ['0', '1px solid', '1px solid'],
    borderRight: ['0', '1px solid', '1px solid'],
    borderTop: ['1px solid', '0', '0'],
    borderColor: ['primaryText.1', 'primaryText.1', 'primaryText.1'],
    boxShadow: ['0 2px 1px 1px', 'none', 'none'],
    display: ['block', 'inline-block', 'inline-block'],
    height: '70px',
    marginLeft: ['0', '16px', '16px'],
    minWidth: '80px',
    verticalAlign: 'middle',
    width: ['100vw', 'auto', 'auto'],
  },
  link: {
    color: 'primaryText.0',
    display: 'inline-block',
    fontFamily: 'menu',
    fontSize: ['20px', '18px', '18px'],
    height: '70px',
    lineHeight: '70px',
    padding: ['0 0 0 20px', '0 24px', '0 24px'],
    textDecoration: 'none',
  },
  imageLink: {
    color: 'primaryText.0',
    display: 'inline-block',
    fontFamily: 'menu',
    fontSize: '20px',
    height: '70px !important',
    lineHeight: '70px !important',
    padding: ['0 0 0 20px', '0', '0'],
    textDecoration: 'none',
    width: '100%',
  },
  image: {
    height: ['40px', '30px', '30px'],
    margin: ['0', '20px 24px', '20px 24px'],
    verticalAlign: 'middle',
    width: ['40px', '30px', '30px'],
  },
  safeName: {
    display: ['inline-block', 'none', 'none'],
    fontFamily: 'menu',
    fontSize: ['20px', '18px', '18px'],
    paddingLeft: '1rem',
    verticalAlign: ['middle', 'top', 'top'],
  },
}
