module.exports = {
  button: {
    background: 'transparent',
    borderBottom: ['none', 'none', 'none'],
    borderLeft: ['0', '1px solid', '1px solid'],
    borderRight: ['0', '1px solid', '1px solid'],
    borderTop: ['1px solid', '0', '0'],
    borderColor: ['primaryText', 'primaryText', 'primaryText'],
    boxShadow: ['0 2px 1px 1px', 'none', 'none'],
    cursor: 'pointer',
    display: ['none', 'inline-block', 'inline-block'],
    height: '70px',
    marginLeft: ['0', '16px', '16px'],
    minWidth: '80px',
    outline: 'none',
    position: 'relative',
    verticalAlign: 'middle',
    width: ['100vw', 'auto', 'auto'],
  },
  link: {
    color: 'primaryLightText',
    display: 'inline-block',
    fontFamily: 'menu',
    fontSize: ['20px', '18px', '18px'],
    height: '70px',
    lineHeight: '70px',
    padding: ['0 0 0 20px', '0 24px', '0 24px'],
    textDecoration: 'none',
  },
  imageLink: {
    color: 'primaryLightText',
    display: 'inline-block',
    fontFamily: 'menu',
    fontSize: '20px',
    height: '70px !important',
    lineHeight: '70px !important',
    padding: ['0 0 0 20px', '0', '0'],
    textDecoration: 'none',
    width: '100%',
  },
  image: {
    height: ['40px', '30px', '30px'],
    margin: ['0', '20px 24px', '20px 24px'],
    verticalAlign: 'middle',
    width: ['40px', '30px', '30px'],
  },
  submenuItem: {
    borderTop: '1px solid',
    borderColor: 'primaryText',
    cursor: 'pointer',
    display: 'block',
    fontFamily: 'menu',
    fontSize: ['20px', '18px', '18px'],
    lineHeight: ['70px', '3rem', '3rem'],
    paddingLeft: '1rem',
    textDecoration: 'none',
    verticalAlign: ['middle', 'top', 'top'],
  },
  submenu: {
    backgroundColor: 'primary',
    display: 'block',
    position: 'absolute',
    right: '0',
    width: '200px',
  },
  hiddenMenu: {
    display: ['block', 'none', 'none'],
  },
}
