module.exports = {
  button: {
    background: 'transparent',
    border: 'none',
    boxShadow: 'none',
    cursor: 'pointer',
    display: ['inline-block', 'inline-block', 'inline-block'],
    height: '50px',
    marginLeft: ['0', '16px', '16px'],
    minWidth: '80px',
    outline: 'none',
    position: 'relative',
    verticalAlign: 'middle',
    width: ['auto', 'auto', 'auto'],
  },
  link: {
    color: 'primaryLightText',
    display: 'inline-block',
    fontFamily: 'menu',
    fontSize: ['20px', '18px', '18px'],
    height: '50px',
    lineHeight: '50px',
    padding: ['0 0 0 20px', '0 24px', '0 24px'],
    textDecoration: 'none',
  },
  imageLink: {
    color: 'primaryLightText',
    display: 'inline-block',
    fontFamily: 'menu',
    fontSize: '20px',
    height: '70px !important',
    lineHeight: '70px !important',
    padding: ['0 0 0 20px', '0', '0'],
    textDecoration: 'none',
    width: '100%',
  },
  image: {
    height: ['40px', '30px', '30px'],
    margin: '0',
    verticalAlign: 'middle',
    width: ['40px', '30px', '30px'],
  },
  submenuItem: {
    '&:hover': {
      backgroundColor: '#0C2340',
    },
    '&:first-of-type': {
      borderTop: 'none',
    },
    backgroundColor: '#0C2340ee',
    color: 'primaryLightText',
    borderTop: '1px solid',
    borderColor: 'primaryText',
    cursor: 'pointer',
    display: 'block',
    fontFamily: 'menu',
    fontSize: ['20px', '18px', '18px'],
    lineHeight: ['70px', '3rem', '3rem'],
    paddingLeft: '1rem',
    textDecoration: 'none',
    verticalAlign: ['middle', 'top', 'top'],
    width: ['100vw', '200px', '200px'],
  },
  submenu: {
    display: 'block',
    position: 'absolute',
    right: ['auto', '0', '0'],
    left: ['0', 'auto', 'auto'],

  },
  hiddenMenu: {
    display: 'none',
  },
}
