version: "2"
checks:
  method-lines:
    config:
      threshold: 100
  similar-code:
    enabled: true
    config:
      threshold: 80
plugins:
  duplication:
    config:
      languages:
        javascript:
          filters:
            - "(object (Identifier PropTypes))"
exclude_paths:
- "**/config/"
- "**/node_modules/"
- "**/test.js"
- "**/__tests__"
- "**/*.css"
- "__mocks__/"
- "**/content/"
- "gatsby-*.js"
- "jest/"
- "yarn.lock"
- ".*.yml"
- "**/*.md"
- "scripts/*"
- "site/*"
- "**/sx.js"
