version: "2"
plugins:
  duplication:
    config:
      languages:
        javascript:
          filters:
            - "s(:property, s(:Identifier, :propTypes))"
exclude_paths:
- "**/config/"
- "**/node_modules/"
- "**/test.js"
- "**/__tests__"
- "**/*.css"
- "__mocks__/"
- "**/content/"
- "gatsby-*.js"
- "jest/"
- "yarn.lock"
- ".*.yml"
- "**/*.md"
- "scripts/*"
- "site/*"
- "**/sx.js"
