module.exports = {
  wrapper: {
    backgroundColor: 'primary',
    display: 'block',
    overflow: 'hidden',
    position: 'absolute',
    width: '100%',
    zIndex: '1',
  },
  heading: {
    color: 'background',
    display: 'inline-block',
    fontFamily: 'heading',
    fontSize: '1.5rem',
    lineHeight: '1.5rem',
    margin: '0',
    padding: '1rem',
    position: 'fixed',
  },
  button: {
    backgroundColor: 'primary',
    color: 'background',
    cursor: 'pointer',
    float: 'right',
    border: 'none',
    borderLeft: '1px solid',
    borderColor: 'primaryText.1',
    lineHeight: '1.5rem',
    padding: '1rem',
  },
  svg: {
    verticalAlign: 'middle',
  },
  content: {
    maxHeight: 'calc(100vh - 80px - 3rem)',
    marginTop: '3rem',
    padding: '1rem',
    overflowX: 'hidden',
    overflowY: 'scroll',
    position: 'relative',
  },
}
