module.exports = {
  overlay: {
    position: 'fixed',
    right: '14rem',
    top: 0,
    height: '100%',
    width: '100%',
    zIndex: 10,
  },
  navigation: {
    m: 0,
    p: '20px',
    position: 'fixed',
    top: '0',
    right: '0px',
    height: '100%',
    width: '14rem',
    background: 'white',
    overflowX: 'hidden',
    overflowY: 'scroll',
    bg: 'gray.2',
    borderLeft: '1px solid gray.4',
    boxShadow: '0 0 8px 0 rgb(0 0 0 / 25%)',
    overflowScrolling: 'touch',
    zIndex: 10,
  },
  closeBox: {
    position: 'absolute',
    zIndex: 10,
    bottom: 0,
    left: 0,
    width: '14rem',
    display: 'flex',
    justifyContent: 'center',
    borderTopColor: 'gray.4',
    borderTopStyle: 'solid',
    borderTopWidth: '1px',
    py: '1rem',
  },
}
