module.exports = {
  deleted: {
    backgroundColor: 'gray.1',
    color: 'white',
    border: '1px solid',
    borderColor: 'gray.1',
    height: '352px',
    lineHeight: '302px',
    margin: '0',
    maxWidth: '800px',
    overflowY: 'scroll',
    padding: '1rem',
    textAlign: 'center',
    width: '100%',
  },
  wrapper: {
    cursor: 'pointer',
    position: 'relative',
  },
  image: {
    backgroundColor: 'white',
    borderRadius: '24px',
    border: '1px solid',
    borderColor: 'gray.1',
    padding: '10px',
    position: 'absolute',
    top: '1rem',
    right: '-1rem',
  },
}
