import React from 'react'
import { shallow } from 'enzyme'
import { SeoContent } from './'
import Helmet from 'react-helmet'
import CanonicalLink from './CanonicalLink'
import MetaTagGroup from './MetaTagGroup'

// This will be generated by useStaticQuery and GraphQL in the parent component
const site = {
  siteMetadata: {
    title: 'Site Title',
    description: 'Site description',
    author: 'Some Person',
    siteUrl: 'https://example.test',
    siteTitle: 'Site Title',
  },
}
const defaultImage = './image.png'
const props = {
  title: 'A New Test Title',
  description: 'A different description',
  image: '/wubbzy.gif',
  lang: 'en-gb',
  pathname: '/some/page',
  site: site,
  defaultImage: defaultImage,
  siteUrl: 'https://example.test',
  siteTitle: 'Site Title',
  author: 'author',
}
describe('SeoContent', () => {
  test('All the props', () => {
    const wrapper = shallow(<SeoContent {...props} />)

    expect(wrapper.find(Helmet).at(0).props().htmlAttributes).toEqual({ 'lang': 'en-gb' })
    expect(wrapper.find(Helmet).at(0).props().title).toEqual('A New Test Title')
    expect(wrapper.find(Helmet).at(0).props().titleTemplate).toEqual('A New Test Title | Site Title')
    expect(wrapper.find(Helmet).at(0).props().meta).toEqual([{
      name: 'description',
      content: 'A different description',
    }])
    expect(wrapper.find(CanonicalLink).props().base).toEqual('https://example.test')
    expect(wrapper.find(CanonicalLink).props().pathname).toEqual('/some/page')
    expect(wrapper.find(MetaTagGroup).length).toEqual(2)
    expect(wrapper.find("meta[name='robots']").exists()).toBeFalsy()
  })
  test('No Index', () => {
    const wrapper = shallow(<SeoContent noIndex {...props} />)
    expect(wrapper.find("meta[name='robots']").props().content).toEqual('noindex')
  })
})
